-- Replace VALUES with your preferred admin details
-- For the password, use the hash generated by the generate_hash.php script
-- Example: INSERT INTO users (name, email, password, role) VALUES ('Admin User', 'admin@example.com', '$2y$10$aVeryLongHashStringFromTheScript', 'admin');

INSERT INTO users (name, email, password, role) 
VALUES (
    'Admin User', 
    'admin@example.com', 
    -- Replace this with the actual hash from generate_hash.php
    '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 
    'admin'
); 